version: '3.8'

services:
  certs:
    container_name: certs
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    command: bash ${ELASTIC_DIR}/config/setup.sh
    user: "0"
    volumes:
      - ./secrets:/secrets/
      - ./setup/setup.sh:${ELASTIC_DIR}/config/setup.sh
      - ./setup/instances.yml:${ELASTIC_DIR}/config/instances.yml:ro
    environment: 
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      STAGING: ${STAGING}

volumes:
  secrets:
    driver: local
  setup:
    driver: local
