instances:
  - name: elasticsearch
    dns: 
      - elasticsearch
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: kibana
    dns: 
      - kibana
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: logstash
    dns: 
      - logstash
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: filebeat
    dns: 
      - filebeat
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1